language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
install:
    - pip install .
    - pip install nose
    - pip install coveralls
script: nosetests --with-coverage --cover-package markovify
after_success: coveralls
